#!/bin/sh
# Configures the GUEST (core.wbx) build: generates a meson cross file for
# miniBox's musl guest toolchain. This core is C++ with exceptions, so it needs
# the C++ flavor of that toolchain (meson-cpp), which carries libstdc++.
#
# Prereq: a built miniBox checkout:
#   meson setup <miniBox>/build/meson-cpp <miniBox> -Dguest_cpp=true
#   ninja -C <miniBox>/build/meson-cpp
#
# Usage: ./waterbox/setup-guest.sh [-m <miniBox dir>]
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
mb="${MINIBOX_DIR:-$HOME/chimera/extern/chimera-common-minibox}"
while getopts "m:" opt; do
	case "$opt" in
		m) mb="$OPTARG" ;;
		*) exit 2 ;;
	esac
done
shift $((OPTIND - 1))
mb="$(cd "$mb" && pwd)"

# prefer a miniBox build that has the guest sysroot; the cpp flavor carries it too
mbuild=""
for candidate in "$mb/build/meson-cpp"; do
	[ -f "$candidate/guest-sysroot/lib/libc.a" ] && { mbuild="$candidate"; break; }
done
[ -n "$mbuild" ] || {
	echo "miniBox C++ guest toolchain missing under $mb/build/meson-cpp." >&2
	echo "Run: meson setup $mb/build/meson-cpp $mb -Dguest_cpp=true && ninja -C $mb/build/meson-cpp" >&2
	exit 1
}
sr="$mbuild/guest-sysroot"
gccver="$(gcc -dumpfullversion)"

mkdir -p "$root/build"
cross="$root/build/guest-cross.ini"

# The waterbox code-model flags + the musl specs; every compile and link of
# the guest gets these.
cat > "$cross" <<EOF
# generated by waterbox/setup-guest.sh - machine-local paths, do not commit
[binaries]
c = 'gcc'
cpp = 'g++'
ar = 'ar'
strip = 'strip'

[host_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
needs_exe_wrapper = true
minibox_dir = '$mb'
minibox_build = '$mbuild'
guest_sysroot = '$sr'

[built-in options]
c_args = ['-specs', '$sr/lib/musl-gcc.specs', '-fvisibility=hidden', '-mcmodel=large', '-mstack-protector-guard=global', '-fno-stack-protector', '-fno-pic', '-fno-pie', '-fcf-protection=none', '-DCHIMERA_GUEST', '-I$mb/extern/emulibc', '-I$mb/source/guest/include', '-I$mb/extern/jsmn']
cpp_args = ['-specs', '$sr/lib/musl-gcc.specs', '-fvisibility=hidden', '-mcmodel=large', '-mstack-protector-guard=global', '-fno-stack-protector', '-fno-pic', '-fno-pie', '-fcf-protection=none', '-fexceptions', '-DCHIMERA_GUEST', '-I$mb/extern/emulibc', '-I$mb/source/guest/include', '-I$mb/extern/jsmn', '-I$sr/include/c++/$gccver', '-I$sr/include/c++/$gccver/x86_64-linux-musl']
c_link_args = ['-specs', '$sr/lib/musl-gcc.specs']
cpp_link_args = ['-specs', '$sr/lib/musl-gcc.specs']
EOF

# -Dminibox_dir explicitly: meson.build's fallback is a path relative to the
# checkout, which only resolves when this repo sits BESIDE a chimera checkout -
# not when it is a submodule inside one (extern/cores/*)
meson setup "$root/build/meson-guest" "$root" --cross-file "$cross" "-Dminibox_dir=$mb" "$@" 2>/dev/null \
	|| meson setup --reconfigure "$root/build/meson-guest" "$root" --cross-file "$cross" "-Dminibox_dir=$mb" "$@"
echo "guest build configured: ninja -C build/meson-guest"
